# Generated by Django 4.1.7 on 2023-03-07 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='caprion',
            new_name='caption',
        ),
    ]
